#!/bin/bash


# Handle initial configuration of Icinga Web 2
if [ ! -f /etc/icingaweb2/config.ini ]; then
  # Create a setup token if there isn't one
  echo "######################################################################"
  chgrp icingaweb2 /etc/icingaweb2/setup.token
  if [ ! -f /etc/icingaweb2/setup.token ]; then
    icingacli setup token create && chgrp icingaweb2 /etc/icingaweb2/setup.token
  else
    echo "The setup token is: $(cat /etc/icingaweb2/setup.token)"
  fi
  echo "You will need this to configure Icinga Web 2."
  echo "######################################################################"
fi

/usr/sbin/apache2ctl -D FOREGROUND
