#!/bin/bash


addgroup --system icingaweb2;
usermod -a -G icingaweb2 www-data; 

# Handle initial configuration of Icinga Web 2
if [ ! -f /etc/icingaweb2/config.ini ]; then
  # Create a setup token if there isn't one
  echo "######################################################################"
  if [ ! -f /etc/icingaweb2/setup.token ]; then
    icingacli setup config directory --group icingaweb2;
    icingacli setup token create;
  else
    echo "The setup token is: $(cat /etc/icingaweb2/setup.token)"
  fi
  echo "You will need this to configure Icinga Web 2."
  echo "######################################################################"
fi

chown root:icingaweb2 /etc/icingaweb2/setup.token
chmod 770 /etc/icingaweb2 /etc/icingaweb2/setup.token
